// AltusFlow 2.0 — Global Admin Mock Data

export const serviceCodes = [
  { code: 'COMP-PANEL', name: 'Comprehensive Panel', description: 'Full biomarker panel — 30 markers', price: 299 },
  { code: 'BASIC-PANEL', name: 'Basic Panel', description: 'Essential biomarkers — 15 markers', price: 149 },
  { code: 'CARDIO-PANEL', name: 'Cardiovascular Panel', description: 'Heart health markers — 12 markers', price: 199 },
  { code: 'THYROID-PANEL', name: 'Thyroid Panel', description: 'Thyroid function markers — 6 markers', price: 129 },
]

export const clients = [
  {
    id: 'CLT001',
    name: 'BodyHealth',
    programName: 'BodyHealth Wellness Program',
    primaryContact: 'Mike Chen',
    primaryContactEmail: 'mike@bodyhealth.com',
    subdomainPrefix: 'bodyhealth',
    logo: null,
    primaryColor: '#0891b2',
    activeMembers: 145,
    ordersMTD: 23,
    totalOrders: 312,
    status: 'Active',
    createdDate: '2024-11-01',
    serviceCodes: ['COMP-PANEL', 'BASIC-PANEL'],
    ghlSubAccount: 'bh-001',
    billingContact: 'finance@bodyhealth.com',
    sslStatus: 'Active',
  },
  {
    id: 'CLT002',
    name: 'VitalLife',
    programName: 'VitalLife Health Monitoring',
    primaryContact: 'Jessica Park',
    primaryContactEmail: 'jpark@vitallife.com',
    subdomainPrefix: 'vitallife',
    logo: null,
    primaryColor: '#7c3aed',
    activeMembers: 87,
    ordersMTD: 14,
    totalOrders: 156,
    status: 'Active',
    createdDate: '2025-01-15',
    serviceCodes: ['CARDIO-PANEL', 'THYROID-PANEL'],
    ghlSubAccount: 'vl-001',
    billingContact: 'billing@vitallife.com',
    sslStatus: 'Active',
  },
  {
    id: 'CLT003',
    name: 'OptimizeHealth',
    programName: 'OptimizeHealth Performance',
    primaryContact: 'Robert Kim',
    primaryContactEmail: 'rkim@optimizehealth.com',
    subdomainPrefix: 'optimizehealth',
    logo: null,
    primaryColor: '#059669',
    activeMembers: 52,
    ordersMTD: 8,
    totalOrders: 67,
    status: 'Active',
    createdDate: '2025-03-01',
    serviceCodes: ['COMP-PANEL', 'CARDIO-PANEL'],
    ghlSubAccount: 'oh-001',
    billingContact: 'admin@optimizehealth.com',
    sslStatus: 'Expiring Soon',
  },
]

export const orders = [
  {
    id: 'ORD001',
    memberId: 'MBR001',
    memberName: 'Sarah Johnson',
    memberEmail: 'sarah.j@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'COMP-PANEL',
    serviceName: 'Comprehensive Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-02-10',
    status: 'Results Ready',
    kitShipDate: '2025-02-13',
    sampleReceivedDate: '2025-02-19',
    resultDate: '2025-02-20',
    exceptionFlag: false,
    exceptions: [],
    crelioOrderId: 'CRELIO-10045',
    shopifyOrderId: 'SHP-7812',
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-02-10T09:00:00' },
      { status: 'Kit Shipped', timestamp: '2025-02-13T14:30:00' },
      { status: 'Sample Received', timestamp: '2025-02-19T10:00:00' },
      { status: 'Processing', timestamp: '2025-02-19T12:00:00' },
      { status: 'Results Ready', timestamp: '2025-02-20T08:00:00' },
    ],
  },
  {
    id: 'ORD002',
    memberId: 'MBR001',
    memberName: 'Sarah Johnson',
    memberEmail: 'sarah.j@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'BASIC-PANEL',
    serviceName: 'Basic Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2024-12-28',
    status: 'Results Ready',
    kitShipDate: '2024-12-31',
    sampleReceivedDate: '2025-01-04',
    resultDate: '2025-01-07',
    exceptionFlag: false,
    exceptions: [],
    crelioOrderId: 'CRELIO-10020',
    shopifyOrderId: 'SHP-7456',
    statusHistory: [
      { status: 'Order Received', timestamp: '2024-12-28T11:00:00' },
      { status: 'Kit Shipped', timestamp: '2024-12-31T09:00:00' },
      { status: 'Sample Received', timestamp: '2025-01-04T14:00:00' },
      { status: 'Processing', timestamp: '2025-01-05T08:00:00' },
      { status: 'Results Ready', timestamp: '2025-01-07T10:00:00' },
    ],
  },
  {
    id: 'ORD003',
    memberId: 'MBR002',
    memberName: 'James Martinez',
    memberEmail: 'james.m@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'COMP-PANEL',
    serviceName: 'Comprehensive Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-02-22',
    status: 'Kit Shipped',
    kitShipDate: '2025-02-25',
    sampleReceivedDate: null,
    resultDate: null,
    exceptionFlag: false,
    exceptions: [],
    crelioOrderId: null,
    shopifyOrderId: 'SHP-7890',
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-02-22T10:00:00' },
      { status: 'Kit Shipped', timestamp: '2025-02-25T13:00:00' },
    ],
  },
  {
    id: 'ORD004',
    memberId: 'MBR003',
    memberName: 'Emily Chen',
    memberEmail: 'emily.c@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'BASIC-PANEL',
    serviceName: 'Basic Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-03-01',
    status: 'Order Received',
    kitShipDate: null,
    sampleReceivedDate: null,
    resultDate: null,
    exceptionFlag: false,
    exceptions: [],
    crelioOrderId: null,
    shopifyOrderId: 'SHP-7920',
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-03-01T09:30:00' },
    ],
  },
  {
    id: 'ORD005',
    memberId: 'MBR004',
    memberName: 'David Wilson',
    memberEmail: 'david.w@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'COMP-PANEL',
    serviceName: 'Comprehensive Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-02-18',
    status: 'Sample Received',
    kitShipDate: '2025-02-21',
    sampleReceivedDate: '2025-02-28',
    resultDate: null,
    exceptionFlag: true,
    exceptions: [
      {
        type: 'Lab Transmission Error',
        detail: 'CrelioHealth API timeout on order transmission. Retry scheduled.',
        timestamp: '2025-02-28T14:30:00',
        resolved: false,
      },
    ],
    crelioOrderId: null,
    shopifyOrderId: 'SHP-7855',
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-02-18T09:00:00' },
      { status: 'Kit Shipped', timestamp: '2025-02-21T11:00:00' },
      { status: 'Sample Received', timestamp: '2025-02-28T09:00:00' },
    ],
  },
  {
    id: 'ORD006',
    memberId: 'MBR005',
    memberName: 'Maria Rodriguez',
    memberEmail: 'maria.r@example.com',
    clientId: 'CLT002',
    clientName: 'VitalLife',
    serviceCode: 'CARDIO-PANEL',
    serviceName: 'Cardiovascular Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-02-25',
    status: 'Results Ready',
    kitShipDate: '2025-02-28',
    sampleReceivedDate: '2025-03-04',
    resultDate: '2025-03-05',
    exceptionFlag: false,
    exceptions: [],
    crelioOrderId: 'CRELIO-10067',
    shopifyOrderId: null,
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-02-25T08:00:00' },
      { status: 'Kit Shipped', timestamp: '2025-02-28T15:00:00' },
      { status: 'Sample Received', timestamp: '2025-03-04T11:00:00' },
      { status: 'Processing', timestamp: '2025-03-04T13:00:00' },
      { status: 'Results Ready', timestamp: '2025-03-05T09:00:00' },
    ],
  },
  {
    id: 'ORD007',
    memberId: 'MBR003',
    memberName: 'Emily Chen',
    memberEmail: 'emily.c@example.com',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    serviceCode: 'BASIC-PANEL',
    serviceName: 'Basic Panel',
    collectionMethod: 'Mail-in Kit',
    orderDate: '2025-02-28',
    status: 'Order Received',
    kitShipDate: null,
    sampleReceivedDate: null,
    resultDate: null,
    exceptionFlag: true,
    exceptions: [
      {
        type: 'Ingestion Warning',
        detail: 'Missing DOB in initial Shopify payload. Auto-resolved via member profile.',
        timestamp: '2025-02-28T09:00:00',
        resolved: true,
      },
    ],
    crelioOrderId: null,
    shopifyOrderId: 'SHP-7915',
    statusHistory: [
      { status: 'Order Received', timestamp: '2025-02-28T09:00:00' },
    ],
  },
]

export const users = [
  {
    id: 'USR001',
    name: 'Alex Thompson',
    email: 'alex@altuxdx.com',
    role: 'GlobalAdmin',
    clientId: null,
    clientName: null,
    lastLogin: '2026-03-09T08:30:00',
    status: 'Active',
    invitedDate: '2024-10-01',
  },
  {
    id: 'USR002',
    name: 'Mike Chen',
    email: 'mike@bodyhealth.com',
    role: 'PAD',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    lastLogin: '2026-03-09T09:15:00',
    status: 'Active',
    invitedDate: '2024-11-05',
  },
  {
    id: 'USR003',
    name: 'Jessica Park',
    email: 'jpark@vitallife.com',
    role: 'PAD',
    clientId: 'CLT002',
    clientName: 'VitalLife',
    lastLogin: '2026-03-08T14:20:00',
    status: 'Active',
    invitedDate: '2025-01-20',
  },
  {
    id: 'USR004',
    name: 'Robert Kim',
    email: 'rkim@optimizehealth.com',
    role: 'PAD',
    clientId: 'CLT003',
    clientName: 'OptimizeHealth',
    lastLogin: '2026-03-07T11:45:00',
    status: 'Active',
    invitedDate: '2025-03-05',
  },
  {
    id: 'USR005',
    name: 'Tom Bradley',
    email: 'tom.b@altuxdx.com',
    role: 'GlobalAdmin',
    clientId: null,
    clientName: null,
    lastLogin: '2026-03-06T16:00:00',
    status: 'Active',
    invitedDate: '2024-10-01',
  },
  {
    id: 'USR006',
    name: 'Lisa Wong',
    email: 'lisa.w@bodyhealth.com',
    role: 'PAD',
    clientId: 'CLT001',
    clientName: 'BodyHealth',
    lastLogin: null,
    status: 'Pending',
    invitedDate: '2026-03-07',
  },
  {
    id: 'USR007',
    name: 'Carlos Reyes',
    email: 'carlos.r@vitallife.com',
    role: 'PAD',
    clientId: 'CLT002',
    clientName: 'VitalLife',
    lastLogin: null,
    status: 'Inactive',
    invitedDate: '2025-06-01',
  },
]

export const ingestionMonitor = [
  {
    id: 'ING001',
    clientSource: 'Shopify / BodyHealth',
    timestamp: '2025-03-05T10:00:00',
    errorType: 'Missing SKU Mapping',
    rawPayload: '{"shopify_order_id":"SHP-7925","sku":"BH-ADVANCED-001","member_email":"newuser@example.com"}',
    reviewed: false,
  },
  {
    id: 'ING002',
    clientSource: 'Shopify / BodyHealth',
    timestamp: '2025-02-28T09:00:00',
    errorType: 'Duplicate Submission',
    rawPayload: '{"shopify_order_id":"SHP-7892","member_email":"emily.c@example.com","service_code":"BASIC-PANEL"}',
    reviewed: true,
  },
]

export const emailTemplates = {
  'Result Ready': {
    trigger: 'Result Ready',
    description: 'Sent when a member\'s lab results are released and available to view.',
    defaultSubject: 'Your {{client_name}} Lab Results Are Ready',
    defaultBody: `Hi {{member_first_name}},

Your {{panel_name}} results are now available to view.

View your results: {{portal_link}}

Best regards,
{{client_name}} Team`,
  },
  'Kit Shipped': {
    trigger: 'Kit Shipped',
    description: 'Sent when SLP confirms the test kit has shipped to the member.',
    defaultSubject: 'Your {{client_name}} Test Kit Is On Its Way',
    defaultBody: `Hi {{member_first_name}},

Great news! Your {{service_name}} kit was shipped on {{ship_date}}.

Activate your kit: {{portal_link}}

Best regards,
{{client_name}} Team`,
  },
  'Order Status Change': {
    trigger: 'Order Status Change',
    description: 'Sent when an order transitions to "Results Ready" status.',
    defaultSubject: 'Your {{client_name}} Order Update',
    defaultBody: `Hi {{member_first_name}},

Your order status has been updated to: {{order_status}}.

Track your order: {{portal_link}}

Best regards,
{{client_name}} Team`,
  },
  'Registration Success': {
    trigger: 'Registration Success',
    description: 'Sent when a new member account is created via PAD enrollment.',
    defaultSubject: 'Welcome to {{client_name}}!',
    defaultBody: `Hi {{member_first_name}},

Welcome to the {{program_name}} program! Your account has been created.

Get started: {{portal_link}}

Best regards,
{{client_name}} Team`,
  },
}

export const invoiceData = {
  CLT001: {
    '2025-01': [
      { serviceCode: 'COMP-PANEL', serviceName: 'Comprehensive Panel', unitCount: 8, unitPrice: 299, lineTotal: 2392 },
      { serviceCode: 'BASIC-PANEL', serviceName: 'Basic Panel', unitCount: 5, unitPrice: 149, lineTotal: 745 },
    ],
    '2025-02': [
      { serviceCode: 'COMP-PANEL', serviceName: 'Comprehensive Panel', unitCount: 11, unitPrice: 299, lineTotal: 3289 },
      { serviceCode: 'BASIC-PANEL', serviceName: 'Basic Panel', unitCount: 7, unitPrice: 149, lineTotal: 1043 },
    ],
    '2025-03': [
      { serviceCode: 'COMP-PANEL', serviceName: 'Comprehensive Panel', unitCount: 5, unitPrice: 299, lineTotal: 1495 },
      { serviceCode: 'BASIC-PANEL', serviceName: 'Basic Panel', unitCount: 4, unitPrice: 149, lineTotal: 596 },
    ],
  },
  CLT002: {
    '2025-02': [
      { serviceCode: 'CARDIO-PANEL', serviceName: 'Cardiovascular Panel', unitCount: 6, unitPrice: 199, lineTotal: 1194 },
      { serviceCode: 'THYROID-PANEL', serviceName: 'Thyroid Panel', unitCount: 4, unitPrice: 129, lineTotal: 516 },
    ],
    '2025-03': [
      { serviceCode: 'CARDIO-PANEL', serviceName: 'Cardiovascular Panel', unitCount: 8, unitPrice: 199, lineTotal: 1592 },
      { serviceCode: 'THYROID-PANEL', serviceName: 'Thyroid Panel', unitCount: 3, unitPrice: 129, lineTotal: 387 },
    ],
  },
  CLT003: {
    '2025-03': [
      { serviceCode: 'COMP-PANEL', serviceName: 'Comprehensive Panel', unitCount: 4, unitPrice: 299, lineTotal: 1196 },
      { serviceCode: 'CARDIO-PANEL', serviceName: 'Cardiovascular Panel', unitCount: 3, unitPrice: 199, lineTotal: 597 },
    ],
  },
}
